---
abstract: 'List of Mailing Lists Manager'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-LMLM
provides:
  Mail::LMLM:
    file: lib/Mail/LMLM.pm
    version: 0.6801
  Mail::LMLM::Object:
    file: lib/Mail/LMLM/Object.pm
    version: 0
  Mail::LMLM::Render:
    file: lib/Mail/LMLM/Render.pm
    version: 0
  Mail::LMLM::Render::HTML:
    file: lib/Mail/LMLM/Render/HTML.pm
    version: 0
  Mail::LMLM::Types::Base:
    file: lib/Mail/LMLM/Types/Base.pm
    version: 0
  Mail::LMLM::Types::Egroups:
    file: lib/Mail/LMLM/Types/Egroups.pm
    version: 0
  Mail::LMLM::Types::Ezmlm:
    file: lib/Mail/LMLM/Types/Ezmlm.pm
    version: 0
  Mail::LMLM::Types::GoogleGroups:
    file: lib/Mail/LMLM/Types/GoogleGroups.pm
    version: 0
  Mail::LMLM::Types::Listar:
    file: lib/Mail/LMLM/Types/Listar.pm
    version: 0
  Mail::LMLM::Types::Listserv:
    file: lib/Mail/LMLM/Types/Listserv.pm
    version: 0
  Mail::LMLM::Types::Mailman:
    file: lib/Mail/LMLM/Types/Mailman.pm
    version: 0
  Mail::LMLM::Types::Majordomo:
    file: lib/Mail/LMLM/Types/Majordomo.pm
    version: 0
requires:
  Test::More: 0
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
version: 0.6801
