---
abstract: 'List of Mailing Lists Manager'
author: []
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-LMLM
provides:
  Mail::LMLM:
    file: lib/Mail/LMLM.pm
    version: 0.6801
  Mail::LMLM::Object:
    file: lib/Mail/LMLM/Object.pm
  Mail::LMLM::Render:
    file: lib/Mail/LMLM/Render.pm
  Mail::LMLM::Render::HTML:
    file: lib/Mail/LMLM/Render/HTML.pm
  Mail::LMLM::Types::Base:
    file: lib/Mail/LMLM/Types/Base.pm
  Mail::LMLM::Types::Egroups:
    file: lib/Mail/LMLM/Types/Egroups.pm
  Mail::LMLM::Types::Ezmlm:
    file: lib/Mail/LMLM/Types/Ezmlm.pm
  Mail::LMLM::Types::GoogleGroups:
    file: lib/Mail/LMLM/Types/GoogleGroups.pm
  Mail::LMLM::Types::Listar:
    file: lib/Mail/LMLM/Types/Listar.pm
  Mail::LMLM::Types::Listserv:
    file: lib/Mail/LMLM/Types/Listserv.pm
  Mail::LMLM::Types::Mailman:
    file: lib/Mail/LMLM/Types/Mailman.pm
  Mail::LMLM::Types::Majordomo:
    file: lib/Mail/LMLM/Types/Majordomo.pm
requires:
  Test::More: 0
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
version: 0.6801
